---
all:
  children:
    production:
      hosts:
        your_remote_host:
          ansible_host: your_remote_ip_or_domain
          ansible_user: your_ssh_user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
