---
all:
  children:
    zerotier:
      hosts:
        zerotier_host:
          ansible_host: "{{ zerotier_ip | default('fdxx::xxxx') }}"  # From ZeroTier status
          ansible_user: cbwinslow
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
