---
- name: Install Apache HTTP Server
  apt:
    name: apache2
    state: present
  become: yes
  when: install_apache_httpd

- name: Start Apache
  systemd:
    name: apache2
    state: started
    enabled: yes
  become: yes
  when: install_apache_httpd
