---
all:
  children:
    tailscale:
      hosts:
        tailscale_host:
          ansible_host: "{{ tailscale_ip | default('100.x.x.x') }}"  # From Tailscale status
          ansible_user: cbwinslow
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
